### ISSUE TITLE
add a persistence layer

### ISSUE THREAD

**Issue by CodeConnoisseur74** [CodeConnoisseur74/pdi-to-do-app#1]
message history from @bbelderbos :

we can try sqlmodel (I will send you a customized chatgpt tutorial ...)

OK I have a customized chatgpt tutorial but also happy to show you

 I made this customized tutorial a while back, can you try get it working with your code to start storing them in a DB table?
https://chat.openai.com/share/175f3b40-eb31-4af4-a287-92d7908e2da4

Great, yep project related stuff here please. Please open 2 PRs:

1. Refactoring of breaking user inputs out of the data manipulation functions (pre-requisite)
2. sqlmodel

**Comment by CodeConnoisseur74** [comment]
@bbelderbos I've created a pull request with the following comments:

I refactored the main by creating a dictionary called 'actions. Each key corresponds to the user's choice in the menu and the value of the corresponding function.

When the user makes a choice, 'actions.get(choice) is used to retrieve the function associated with that choice.

I the user makes a valid choice, the function is called, otherwise,an error message is printed.

Now each action is defined in it's own function (No more 'stairway of elifs').

I welcome your feedback :)

**Comment by CodeConnoisseur74** [comment]
@bbelderbos I'm not sure what's going on here. I got an error saying the sqlmodel wasn't installed. Same thing happened with pre-commit. The only thing that changed was I moved the project folder locally from home to py-projects folder. Here is the current file structure of the project:

![pdi-to-do-file-structure](https://github.com/CodeConnoisseur74/pdi-to-do-app/assets/106032462/52dbfab5-d002-4d2b-9da0-c5d58d10f66e)

Does this have to do with moving it to the py-projects folder? Still weird. I shouldn't have to install everything twice.

**Comment by bbelderbos** [comment]
Hm not sure, can you delete and recreate the virtual environment? 

Do you use vs code for this? If so what about using the command line for this from now on?

```
python3 -m venv venv 
source venv/bin/activate
```

Then install the libraries again:

```
pip install sqlmodel pre-commit
```

(You could also install pre-commit "globally" using pipx, but also ok to skip for now to focus on the mvp code)

Let me know please ...

**Comment by CodeConnoisseur74** [comment]
@bbelderbos Yeah I'll work on that. I always use the command line for venv. VScode has the feature but it was problematic in the past. I'll delete and recreate the venv environment as well as follow the steps.

**Comment by CodeConnoisseur74** [comment]
@bbelderbos I just spent all morning so far trying to fix this. I deleted the .venv. Now I can't create one at all. 

It keeps telling me: /usr/bin/python: No module named venv.venv

I can't checkout of the sqlmodel branch as I didn't commit them. when I try to , it won't let me. 

I've never seen .mypy_cache in my lifetime. The only thng I can do is perhaps, start over in a new repo and copy these messages over in the new repo. I'm at a loss here.

**Comment by CodeConnoisseur74** [comment]
@bbelderbos here is the git status:

![git-status1](https://github.com/CodeConnoisseur74/pdi-to-do-app/assets/106032462/e3a0b61a-c072-48e4-b1be-85b4e62c4018)
![git-status2](https://github.com/CodeConnoisseur74/pdi-to-do-app/assets/106032462/37b441ad-54d3-4a53-908d-516a7a2bc91c)

**Comment by bbelderbos** [comment]
Nice, it seems pre-commit works again no?

The command is `python -m venv venv` (not . in between)

The first venv is the module, the second one is the name of the directory it will create, if you want .venv rather, it would be: `python -m venv .venv`

Does that work?

**Comment by CodeConnoisseur74** [comment]
@bbelderbos Oh I mixed those two up? Yeah it was time to take a break. Having lunch now and back at it in the afternoon.

**Comment by CodeConnoisseur74** [comment]
@bbelderbos To pre-commit install sqlmodel, do I have to change the pre-commit.yaml file?

**Comment by bbelderbos** [comment]
No, they are unrelated. Pre-commit is to automatically run your linters / checkers upon git commit. 

sqlmodel is the package we'll use for the database persistence code in your app. Don't worry about pre-commit too much right now, just `pip install sqlmodel` into your new (activated) virtual env and do the following:

- create a Todo model/class in models.py
- create the engine and 3 functions in db.py (importing the Todo model from models.py): `show_todos`, `add_todo`, `complete_todo` - these functions should contain the DB logic to store and retrieve todo items, using the `Session` object as per the ChatGPT example.

Ok?

**Comment by CodeConnoisseur74** [comment]
@bbelderbos No problem. 

I'm still facing the issue of when I checkout into the sql branch, it tells me that sql model is not installed. 

I may have messed up my git workflow somehow. I have to review that. 

I just tried to commit again and getting some error. 

I was getting so frustrated that I went for a walk. 

I had to switch gears for a bit.

**Comment by bbelderbos** [comment]
Stepping away is important yes. 
What error did you get? And after which steps(s) exactly?

**Comment by CodeConnoisseur74** [comment]
Let me look at that now and I'll send you what I've looked up and sources plus error.

**Comment by CodeConnoisseur74** [comment]
@bbelderbos 

![db-error1](https://github.com/CodeConnoisseur74/pdi-to-do-app/assets/106032462/8d0846fe-b9f8-4810-99a0-02cd0de2679f)

**Comment by bbelderbos** [comment]
I've hit this, pretty annoying, you could ignore that last violation.

However, I think the `mypy` thing is a distraction for now, can you remove it from your pre-commit yaml so it does not do those checks for now. Ok?

The flake8 violations should be easier to fix.

**Comment by CodeConnoisseur74** [comment]
@bbelderbos  Uhhhmmmm Perhaps this has something to do with it: 

![file-structure1](https://github.com/CodeConnoisseur74/pdi-to-do-app/assets/106032462/bfdf66d4-cdc8-4cf4-a2f6-a1ca729abacb)
![file-structure2](https://github.com/CodeConnoisseur74/pdi-to-do-app/assets/106032462/fd2e590f-93a7-4843-be60-9926c79ab484)
![file-structure3](https://github.com/CodeConnoisseur74/pdi-to-do-app/assets/10603
![file-structure-4](https://github.com/CodeConnoisseur74/pdi-to-do-app/assets/106032462/4828910c-41b4-4579-9997-ea0e5b4c82c9)
2462/357984d4-e309-4998-ad1a-a2207b3fe5ae)


You can keep this for future PDI students: 

You're welcome hahaha

Definately a scenario where two is not bette than one. haha

**Comment by CodeConnoisseur74** [comment]
@bbelderbos 

Google Query:

no module named sqlmodel

source:

https://blog.finxter.com/fixed-modulenotfounderror-no-module-named-sqlmodel/

**Comment by bbelderbos** [comment]
Thanks, not sure what to make of the screenshots?

I think we need to run through this together on zoom today. First see what might be broken and if not obvious start from scratch with a new venv and install sqlmodel. This is weird.

**Comment by CodeConnoisseur74** [comment]
Review of Captstone project:

file structure ok. 

main.py: Added two functions to call from the db.


Think of 3 to 5 features to add to the project. i.e: calendar, dates, etc.

**Comment by CodeConnoisseur74** [comment]
@bbelderbos Yeah so I'mback where I was on thursday with this project. None of the change saved for the first time since I started coding. I didn't push my changes. It's bizarre. VSCode has updated a bunch of times and had  a friend of mine expereincing the same thing in Django over the weekend.

**Comment by CodeConnoisseur74** [comment]
![changes in working tree](https://github.com/CodeConnoisseur74/pdi-to-do-app/assets/106032462/f8bdcc76-b5dd-4414-a681-93027faeee21)

@bbelderbos I found the issue. It'sa git thing. i'll fix this and create a pull request. 

Three Features:

1. Calendar to book tasks
2. set reminders
3. rank tasks in level of priority : Important , regular, can wait

**Comment by bbelderbos** [comment]
cool, what's the git thing?

cool, those are nicely challenging:
- calendar - how would that work?
- reminders = cool, so would add another table for that right? (we will discuss tomorrow, but that would be a one-to-many of todo > reminder)
- prios - for that you also need to assign prios when setting right, so extra column on todo table?

**Comment by CodeConnoisseur74** [comment]
@bbelderbos 

Ok so I messed it up. Changes got unstaged.

**Comment by bbelderbos** [comment]
What happened, what did you do exactly?

**Comment by CodeConnoisseur74** [comment]
@bbelderbos I accidentally unstaged the changes that were made on friday. I'm trying to find out how to restore them.

**Comment by bbelderbos** [comment]
so the Friday changes you did not commit, you staged them?

git stash list

would be the command

git stash pop

brings the changes back into your staging area, but then you need to either stage them again or (better) commit them to not lose them

**Comment by bbelderbos** [comment]
regardless, worst case if they are lost, they should be reproducible again with what you learned so maybe do that first on a new branch and open me a PR so we're on the same page, then we go with the first feature out of 3, which one would that be?

**Comment by CodeConnoisseur74** [comment]
@bbelderbos Calendar: Would be used to schedule tasks, much like google calendar or even organic :) 

Perhaps we can start with the reminders. I'm  not familiar with Tables yet so this would be great to go over with tomorrow's lesson. Ok, I can get those changes back. I got a little frustrated and went for a little ten minutes drive with some music and had a bite to eat. Now I'm back again and can take a fresh look at it. 

Feel free to suggest a bite. I know the Capstone is the focus. However, a bite here and there wouldn't hurt. :)

**Comment by CodeConnoisseur74** [comment]
@bbelderbos So I've been at this with intermittent  breaks all evening and I've confused myself more.  I thought I had it fixed and committed it to push the code and got this:

error:

An error occurred when fetching the repository: Missing or invalid credentials. Error: connect ENOENT /run/user/1001/vscode-git-7164e4b691.sock at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) { errno: -2, code: 'ENOENT', syscall: 'connect', address: '/run/user/1001/vscode-git-7164e4b691.sock' } Missing or invalid credentials. Error: connect ENOENT /run/user/1001/vscode-git-7164e4b691.sock at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) { errno: -2, code: 'ENOENT', syscall: 'connect', address: '/run/user/1001/vscode-git-7164e4b691.sock' } remote: Repository not found. fatal: Authentication failed for 'https://github.com/CodeConnoisseur74/pdi-to-do-app.git/'

I've just spent an hour trying to fix this as something is wrong with the SSH key. My brain is way too fried at this point. 

I'll have to look at it with fresh eyes tomorrow.

**Comment by bbelderbos** [comment]
Done! great work!

**Comment by bbelderbos** [comment]
> @bbelderbos So I've been at this with intermittent breaks all evening and I've confused myself more. I thought I had it fixed and committed it to push the code and got this:
> 
> error:
> 
> An error occurred when fetching the repository: Missing or invalid credentials. Error: connect ENOENT /run/user/1001/vscode-git-7164e4b691.sock at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) { errno: -2, code: 'ENOENT', syscall: 'connect', address: '/run/user/1001/vscode-git-7164e4b691.sock' } Missing or invalid credentials. Error: connect ENOENT /run/user/1001/vscode-git-7164e4b691.sock at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) { errno: -2, code: 'ENOENT', syscall: 'connect', address: '/run/user/1001/vscode-git-7164e4b691.sock' } remote: Repository not found. fatal: Authentication failed for 'https://github.com/CodeConnoisseur74/pdi-to-do-app.git/'
> 
> I've just spent an hour trying to fix this as something is wrong with the SSH key. My brain is way too fried at this point.
> 
> I'll have to look at it with fresh eyes tomorrow.

ah I did "see" it in the sense I had this open in a tab to review, glad it's solved now.
